# Generated by Django 5.1.2 on 2024-10-25 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores_artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='data_doacao',
            new_name='data_donacao',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='telefone',
        ),
        migrations.AddField(
            model_name='doador',
            name='data_ultima_doacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
